import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Upload, MessageSquare, Zap } from "lucide-react";
import { Link } from "react-router-dom";
import { SignedIn, SignedOut, SignInButton } from "@clerk/clerk-react";

const HeroSection = () => {
  const handleGetStarted = () => {
    const element = document.querySelector("#get-started");
    element?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <section id="home" className="relative py-20 lg:py-32 overflow-hidden">
      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center">
          {/* Badge */}
          <div className="inline-flex items-center px-4 py-2 rounded-full bg-blue-50 text-blue-700 text-sm font-medium mb-8 border border-blue-100">
            <Zap className="w-4 h-4 mr-2" />
            AI-Powered Specification Analysis
          </div>

          {/* Main heading */}
          <h1 className="text-5xl lg:text-7xl font-bold text-slate-900 mb-6 leading-tight">
            Understand
            <span className="text-gradient block">Specifications</span>
            Instantly with AI
          </h1>

          {/* Subheading */}
          <p className="text-xl lg:text-2xl text-slate-600 mb-12 max-w-4xl mx-auto leading-relaxed">
            Upload your manufacturing documents and get instant, intelligent
            answers about material standards, tolerances, welding codes, and any
            technical detail.
          </p>

          {/* CTA Buttons */}
          <div className="grid sm:grid-cols-2 gap-6 justify-center mb-16 max-w-4xl mx-auto">
            {/* Chat with AI Card */}
            <div className="relative bg-white/70 backdrop-blur-sm border border-slate-200/60 p-8 rounded-2xl group hover:bg-white/90 hover:border-blue-200/80 transition-all duration-300 hover:shadow-lg">
              <div className="relative z-10">
                <div className="flex items-center justify-center mb-6">
                  <div className="w-14 h-14 bg-gradient-to-br from-blue-50 to-blue-100 rounded-xl flex items-center justify-center group-hover:from-blue-100 group-hover:to-blue-200 transition-colors duration-300">
                    <Upload className="w-7 h-7 text-blue-600" />
                  </div>
                </div>
                <h3 className="text-xl font-semibold text-slate-900 mb-3">
                  Chat with AI
                </h3>
                <p className="text-slate-600 mb-6 text-sm leading-relaxed">
                  Get instant answers generated by AI trained on your documents.
                </p>
                <SignedIn>
                  <Link to="/Ai-chat">
                    <Button className="w-full bg-blue-600 hover:bg-blue-700 text-white font-medium px-6 py-3 rounded-xl transition-all duration-200 hover:shadow-md">
                      Try Now
                    </Button>
                  </Link>
                </SignedIn>
                <SignedOut>
                  <Link to="/sign-in">
                    <Button className="w-full bg-blue-600 hover:bg-blue-700 text-white font-medium px-6 py-3 rounded-xl transition-all duration-200 hover:shadow-md">
                      Sign In to Try
                    </Button>
                  </Link>
                </SignedOut>
              </div>
            </div>

            {/* Expert Team Response Card */}
            <div className="relative bg-white/70 backdrop-blur-sm border border-slate-200/60 p-8 rounded-2xl group hover:bg-white/90 hover:border-slate-300/80 transition-all duration-300 hover:shadow-lg">
              <div className="relative z-10">
                <div className="flex items-center justify-center mb-6">
                  <div className="w-14 h-14 bg-gradient-to-br from-slate-50 to-slate-100 rounded-xl flex items-center justify-center group-hover:from-slate-100 group-hover:to-slate-200 transition-colors duration-300">
                    <MessageSquare className="w-7 h-7 text-slate-700" />
                  </div>
                </div>
                <h3 className="text-xl font-semibold text-slate-900 mb-3">
                  Expert Team Response
                </h3>
                <p className="text-slate-600 mb-6 text-sm leading-relaxed">
                  Connect with our team of engineers for personalized help and
                  expert guidance.
                </p>
                <SignedIn>
                  <Link to="/get-started">
                    <Button className="w-full bg-slate-800 hover:bg-slate-900 text-white font-medium px-6 py-3 rounded-xl transition-all duration-200 hover:shadow-md">
                      Get Started
                    </Button>
                  </Link>
                </SignedIn>
                <SignedOut>
                  <Link to="/sign-in">
                    <Button className="w-full bg-slate-800 hover:bg-slate-900 text-white font-medium px-6 py-3 rounded-xl transition-all duration-200 hover:shadow-md">
                      Sign In to Start
                    </Button>
                  </Link>
                </SignedOut>
              </div>
            </div>
          </div>

          {/* Feature highlights */}
          <div className="grid md:grid-cols-3 gap-6 max-w-4xl mx-auto">
            <Card className="p-6 bg-white/60 backdrop-blur-sm border border-slate-200/60 hover:bg-white/80 hover:border-slate-300/80 transition-all duration-300 group rounded-2xl">
              <div className="text-center">
                <div className="w-12 h-12 bg-gradient-to-br from-blue-50 to-blue-100 rounded-xl flex items-center justify-center mb-4 mx-auto group-hover:from-blue-100 group-hover:to-blue-200 transition-colors duration-300">
                  <Upload className="w-6 h-6 text-blue-600" />
                </div>
                <h3 className="text-lg font-semibold text-slate-900 mb-3">
                  Instant Upload
                </h3>
                <p className="text-slate-600 text-sm leading-relaxed">
                  Drag and drop PDFs, DOCX, and other technical documents
                </p>
              </div>
            </Card>

            <Card className="p-6 bg-white/60 backdrop-blur-sm border border-slate-200/60 hover:bg-white/80 hover:border-slate-300/80 transition-all duration-300 group rounded-2xl">
              <div className="text-center">
                <div className="w-12 h-12 bg-gradient-to-br from-green-50 to-green-100 rounded-xl flex items-center justify-center mb-4 mx-auto group-hover:from-green-100 group-hover:to-green-200 transition-colors duration-300">
                  <MessageSquare className="w-6 h-6 text-green-600" />
                </div>
                <h3 className="text-lg font-semibold text-slate-900 mb-3">
                  AI Chat Interface
                </h3>
                <p className="text-slate-600 text-sm leading-relaxed">
                  Ask questions in natural language and get precise answers
                </p>
              </div>
            </Card>

            <Card className="p-6 bg-white/60 backdrop-blur-sm border border-slate-200/60 hover:bg-white/80 hover:border-slate-300/80 transition-all duration-300 group rounded-2xl">
              <div className="text-center">
                <div className="w-12 h-12 bg-gradient-to-br from-purple-50 to-purple-100 rounded-xl flex items-center justify-center mb-4 mx-auto group-hover:from-purple-100 group-hover:to-purple-200 transition-colors duration-300">
                  <Zap className="w-6 h-6 text-purple-600" />
                </div>
                <h3 className="text-lg font-semibold text-slate-900 mb-3">
                  Real-time Results
                </h3>
                <p className="text-slate-600 text-sm leading-relaxed">
                  Get instant answers about standards, codes, and specifications
                </p>
              </div>
            </Card>
          </div>
        </div>
      </div>
    </section>
  );
};

export default HeroSection;
