

import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Upload, MessageSquare, Zap } from "lucide-react";

const HeroSection = () => {
  const handleGetStarted = () => {
    const element = document.querySelector("#get-started");
    element?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <section id="home" className="relative min-h-screen flex items-center justify-center overflow-hidden">
      {/* Background with image and overlay */}
      <div className="absolute inset-0">
        {/* Background image */}
        <div 
          className="absolute inset-0 bg-cover bg-center bg-no-repeat"
          style={{
            backgroundImage: "url('public/Header.jpg')"
          }}
        ></div>
        
        {/* Gradient overlay for better text readability */}
        <div className="absolute inset-0 bg-gradient-to-br from-white/90 via-white/70 to-blue-50/80"></div>
        
        {/* Additional subtle pattern overlay */}
        <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/20 to-transparent"></div>
      </div>

      {/* Floating elements for visual interest */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-20 left-10 w-32 h-32 bg-blue-200/20 rounded-full blur-xl animate-pulse"></div>
        <div className="absolute bottom-20 right-10 w-40 h-40 bg-pink-200/20 rounded-full blur-xl animate-pulse delay-1000"></div>
        <div className="absolute top-1/2 left-1/4 w-24 h-24 bg-purple-200/20 rounded-full blur-xl animate-pulse delay-500"></div>
      </div>

      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="text-center">
          {/* Animated badge */}
          <div className="inline-flex items-center px-6 py-3 rounded-full bg-gradient-to-r from-blue-500 to-purple-500 text-white text-sm font-medium mb-8 shadow-lg hover:shadow-xl transition-all duration-300 hover:scale-105">
            <Zap className="w-4 h-4 mr-2 animate-pulse" />
            AI-Powered Specification Analysis
          </div>

          {/* Main heading with enhanced typography */}
          <h1 className="text-6xl lg:text-8xl font-bold mb-6 leading-tight">
            <span className="text-slate-900">Understand</span>
            <span className="block bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 bg-clip-text text-transparent animate-pulse">
              Specifications
            </span>
            <span className="text-slate-900">Instantly with AI</span>
          </h1>

          {/* Enhanced subheading */}
          <p className="text-xl lg:text-2xl text-slate-700 mb-16 max-w-4xl mx-auto leading-relaxed font-light">
            Upload your manufacturing documents and get instant, intelligent
            answers about material standards, tolerances, welding codes, and any
            technical detail.
          </p>

          {/* Enhanced CTA Cards */}
          <div className="grid sm:grid-cols-2 gap-8 justify-center mb-20 max-w-5xl mx-auto">
            {/* AI Response Card */}
            <div className="relative group cursor-pointer">
              <div className="absolute -inset-1 bg-gradient-to-r from-blue-600 to-purple-600 rounded-3xl blur opacity-60 group-hover:opacity-100 transition duration-300"></div>
              <div className="relative bg-gradient-to-br from-blue-600 to-purple-600 text-white p-8 rounded-3xl shadow-2xl hover:scale-[1.02] transition-all duration-300 overflow-hidden">
                {/* Animated background pattern */}
                <div className="absolute inset-0 bg-white/10 opacity-0 group-hover:opacity-100 transition-opacity duration-300 rounded-3xl"></div>
                
                <div className="relative z-10">
                  <div className="flex items-center mb-6">
                    <div className="bg-white/20 p-3 rounded-full mr-4 group-hover:rotate-12 transition-transform duration-300">
                      <Upload className="w-6 h-6" />
                    </div>
                    <h3 className="text-2xl font-bold">AI Response</h3>
                  </div>
                  <p className="mb-6 text-white/90 text-lg">
                    Get instant answers generated by AI trained on your documents.
                  </p>
                  <Button className="bg-white text-blue-600 font-bold px-8 py-4 rounded-full hover:bg-blue-50 transition-all duration-300 hover:scale-105 shadow-lg text-lg">
                    Try Now →
                  </Button>
                </div>
              </div>
            </div>

            {/* Human Response Card */}
            <div className="relative group cursor-pointer">
              <div className="absolute -inset-1 bg-gradient-to-r from-pink-500 to-blue-500 rounded-3xl blur opacity-60 group-hover:opacity-100 transition duration-300"></div>
              <div className="relative bg-white/90 backdrop-blur-lg border border-white/20 p-8 rounded-3xl shadow-2xl hover:scale-[1.02] transition-all duration-300">
                <div className="relative z-10">
                  <div className="flex items-center mb-6">
                    <div className="bg-gradient-to-r from-pink-500 to-blue-500 p-3 rounded-full mr-4 group-hover:scale-110 transition-transform duration-300">
                      <MessageSquare className="w-6 h-6 text-white" />
                    </div>
                    <h3 className="text-2xl font-bold text-slate-900">Human Response</h3>
                  </div>
                  <p className="mb-6 text-slate-700 text-lg">
                    Connect with real experts for personalized help and support.
                  </p>
                  <Button className="bg-gradient-to-r from-pink-500 to-blue-500 text-white px-8 py-4 rounded-full hover:scale-105 transition-all duration-300 shadow-lg text-lg font-bold">
                    Get Started →
                  </Button>
                </div>
              </div>
            </div>
          </div>

          {/* Enhanced feature highlights */}
          <div className="grid md:grid-cols-3 gap-8 max-w-6xl mx-auto">
            <Card className="p-8 bg-white/80 backdrop-blur-lg border-0 shadow-xl hover:shadow-2xl transition-all duration-300 hover:scale-105 rounded-2xl group">
              <div className="w-16 h-16 bg-gradient-to-r from-blue-500 to-purple-500 rounded-2xl flex items-center justify-center mb-6 mx-auto group-hover:rotate-12 transition-transform duration-300">
                <Upload className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-xl font-bold text-slate-900 mb-4">
                Instant Upload
              </h3>
              <p className="text-slate-600 text-lg">
                Drag and drop PDFs, DOCX, and other technical documents
              </p>
            </Card>

            <Card className="p-8 bg-white/80 backdrop-blur-lg border-0 shadow-xl hover:shadow-2xl transition-all duration-300 hover:scale-105 rounded-2xl group">
              <div className="w-16 h-16 bg-gradient-to-r from-purple-500 to-pink-500 rounded-2xl flex items-center justify-center mb-6 mx-auto group-hover:rotate-12 transition-transform duration-300">
                <MessageSquare className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-xl font-bold text-slate-900 mb-4">
                AI Chat Interface
              </h3>
              <p className="text-slate-600 text-lg">
                Ask questions in natural language and get precise answers
              </p>
            </Card>

            <Card className="p-8 bg-white/80 backdrop-blur-lg border-0 shadow-xl hover:shadow-2xl transition-all duration-300 hover:scale-105 rounded-2xl group">
              <div className="w-16 h-16 bg-gradient-to-r from-pink-500 to-blue-500 rounded-2xl flex items-center justify-center mb-6 mx-auto group-hover:rotate-12 transition-transform duration-300">
                <Zap className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-xl font-bold text-slate-900 mb-4">
                Real-time Results
              </h3>
              <p className="text-slate-600 text-lg">
                Get instant answers about standards, codes, and specifications
              </p>
            </Card>
          </div>
        </div>
      </div>
    </section>
  );
};

export default HeroSection;